export const SCHEMA_VERSIONS = {
  workThread: "WorkThreadV1",
  recoveryCapsule: "RecoveryCapsuleV1",
  actionRequest: "ActionRequestV1",
  actionResult: "ActionResultV1",
  automationDefinition: "AutomationDefinitionV1",
  executionEvent: "ExecutionEventV1",
  userPreferences: "UserPreferencesV1",
  actionPermission: "ActionPermissionV1",
  syncQueueItem: "SyncQueueItemV1",
  threadUpdate: "ThreadUpdateV1",
  progressNote: "ProgressNoteV1",
  contextItem: "ContextItemV1",
  contextSnapshot: "ContextSnapshotV1",
  resumeCard: "ResumeCardV1",
  commitmentCandidate: "CommitmentCandidateV1",
  proposedAction: "ProposedActionV1",
  syncEvent: "SyncEventV1",
  contextPacket: "ContextPacketV1"
} as const;
